controller_manager:
  ros__parameters:
    wheel_joint_controller:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel: ['left_wheel_1_1', 'left_wheel_2_1', 'left_wheel_3_1']
      right_wheel: ['right_wheel_1_1', 'right_wheel_2_1', 'right_wheel_3_1']
      publish_rate: 50
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.01, 0.01, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.01, 0.01, 0.01]
      odom_frame: odom
      base_frame: base_link
      cmd_vel_timeout: 0.25
      velocity_rolling_window_size: 2

  <arg name="urdf_file" default="$(find xacro)/xacro --inorder '$(find isro_description)/urdf/isro.xacro'"/>
  <param name="robot_description" command="$(arg urdf_file)" />